name: Hugo Build and Deploy

on:
  push:
    branches:
    - main

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
            hugo-version: latest
      
      - name: Get Theme
        run: git clone https://github.com/philipp-schuetz/pugo /home/runner/work/hugo-site/hugo-site/themes/pugo
        
      - name: Build
        run: hugo --minify

      - name: Deploy over FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
            server: blog.philippschuetz.de
            username: ${{ secrets.FTP_USERNAME }}
            password: ${{ secrets.FTP_PASSWORD }}
            server-dir: /
            local-dir: ./public/